config/routes.rb
Rails.application.routes.draw do
  namespace :auth do
    get '/log_in', action: 'log_in'
    get '/log_in_as_admin', action: 'log_in_as_admin'
    get '/log_out', action: 'log_out'
  end

  resources :repairs, except: :delete do
    resources :repair_updates, path: 'updates', only: :create
  end

  namespace :triage do
    get '/select', action: 'select_issue_type'
    get '/solution', action: 'solution'
    get '/done', action: 'done'
  end

  root 'landing#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/repair.rb
class Repair < ApplicationRecord
  has_many :updates, class_name: 'RepairUpdate', dependent: :destroy

  enum issue_type: %i[
    other no_electricity no_gas no_heating no_water smell_gas water_leak
    water_leak_electrics not_secure_access exposed_wiring alarm_beeping
  ]

  validates :name, presence: true
  validates :address, presence: true
  validates :email, presence: true
  validates :issue_type, presence: true
  validates :description, presence: true

  def status
    last_update = updates.last

    if last_update
      last_update.status
    else
      RepairUpdate.statuses.key 0
    end
  end
end

app/models/repair_update.rb
class RepairUpdate < ApplicationRecord
  belongs_to :repair

  enum status: %i[reported in_progress done]

  validates :status, presence: true
  validates :description, presence: true
  validates :repair_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :admin

  private

  def admin
    @admin = session[:logged_in_as_admin]
  end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  def log_in
    session[:logged_in] = true

    redirect_back fallback_location: root_path
  end

  def log_in_as_admin
    session[:logged_in] = true
    session[:logged_in_as_admin] = true

    redirect_back fallback_location: root_path
  end

  def log_out
    session.delete(:logged_in)
    session.delete(:logged_in_as_admin)

    redirect_back fallback_location: root_path
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
    redirect_to triage_select_path
  end
end

app/controllers/repair_updates_controller.rb
class RepairUpdatesController < ApplicationController
  def create
    @repair = Repair.find(params[:repair_id])
    @update = RepairUpdate.new(update_params.merge(repair: @repair))

    if @update.save
      RepairMailer.with(email: @repair.email, repair_id: @repair.id)
                  .updated_email.deliver_now

      redirect_to @repair
    else
      render 'repairs/show'
    end
  end

  private

  def update_params
    params.require(:repair_update).permit(:status, :description)
  end
end

app/controllers/repairs_controller.rb
class RepairsController < ApplicationController
  def index
    if @admin
      @repairs = Repair.all
    else
      redirect_to root_path
    end
  end

  def show
    @repair = Repair.find(params[:id])
    @update = RepairUpdate.new
  end

  def new
    @repair = Repair.new(repair_params)
  end

  def edit
    if @admin
      @repair = Repair.find(params[:id])
    else
      redirect_to action: :show, id: params[:id]
    end
  end

  def create
    @repair = Repair.new(repair_params)

    if @repair.save
      RepairMailer.with(email: @repair.email, repair_id: @repair.id)
                  .reported_email.deliver_later

      redirect_to @repair
    else
      render 'new'
    end
  end

  def update
    if @admin
      @repair = Repair.find(params[:id])

      if @repair.update(repair_params)
        redirect_to @repair
      else
        render 'edit'
      end
    else
      redirect_to action: :show, id: params[:id]
    end
  end

  private

  def repair_params
    params.require(:repair).permit(
      :name, :address, :email, :issue_type, :description, :status
    )
  end
end

app/controllers/triage_controller.rb
class TriageController < ApplicationController
  def select_issue_type; end

  def solution
    @issue_type = params[:issue_type]

    case @issue_type
    when 'no_electricity'
      @help_content = 'Do something to fix the electricity!'
    when 'no_gas'
      @help_content = 'Do something about the gas.'
    else
      redirect_to_repair @issue_type
    end
  end

  def done
    redirect_to_repair params[:issue_type] if params[:no]
  end

  private

  def redirect_to_repair(issue_type)
    redirect_to new_repair_path(repair: { issue_type: issue_type })
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/repair_updates_helper.rb
module RepairUpdatesHelper
end

app/helpers/repairs_helper.rb
module RepairsHelper
  def sorted_issue_types
    Repair.issue_types.sort do |a, b|
      if a[0] == 'other'
        1
      elsif b[0] == 'other'
        -1
      else
        a <=> b
      end
    end
  end
end

app/helpers/triage_helper.rb
module TriageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Doberman</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if session[:logged_in] %>
        Logged in<%= ' as admin' if @admin %>
        <%= link_to 'Log out', auth_log_out_path %>
      <% else %>
        <%= link_to 'Log in', auth_log_in_path %>
        <%= link_to 'Log in as admin', auth_log_in_as_admin_path %>
      <% end %>

      |
      <%= link_to 'New issue', triage_select_path %>
      <%= link_to 'All Repairs', repairs_path if @admin %>
    </header>

    <%= yield %>
  </body>
</html>

app/views/repair_updates/_form.html.erb
<% if @update.errors.any? %>
  <h2>
    <%= pluralize(@update.errors.count, "error") %>
    prohibited this update from being saved:
  </h2>

  <ul>
    <% @update.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: [ @repair, @update ], local: true do |form| %>
  <p>
    <%= form.label :status %><br>
    <%= form.select :status, options_for_select(RepairUpdate.statuses.map { |t| [t[0].humanize, t[0]] }, @repair.status) %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/repair_updates/_repair_update.html.erb
<p>
  <strong>Status:</strong>
  <%= repair_update.status.humanize %>
</p>

<p>
  <strong>Description:</strong>
  <%= repair_update.description %>
</p>

app/views/repairs/edit.html.erb
<% if @repair.errors.any? %>
  <h2>
    <%= pluralize(@repair.errors.count, "error") %>
    prohibited this repair from being saved:
  </h2>

  <ul>
    <% @repair.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @repair, local: true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :address %><br>
    <%= form.text_area :address %>
  </p>

  <p>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </p>

  <p>
    <%= form.label :issue_type %><br>
    <%= form.select :issue_type, options_for_select(sorted_issue_types.map { |t| [t[0].humanize, t[0]] }, @repair.issue_type) %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/repairs/index.html.erb
<h1>All repairs</h1>

<% @repairs.each do |repair| %>
  <p>
    <%= repair.issue_type.humanize %> (<%= repair.status.humanize %>) - <%= link_to 'Show', repair_path(repair) %> <%= link_to 'Edit', edit_repair_path(repair) %>
  </p>
<% end %>

app/views/repairs/new.html.erb
<% if @repair.errors.any? %>
  <h2>
    <%= pluralize(@repair.errors.count, "error") %>
    prohibited this repair from being saved:
  </h2>

  <ul>
    <% @repair.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @repair, url: repairs_path, local: true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :address %><br>
    <%= form.text_area :address %>
  </p>

  <p>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </p>

  <p>
    <%= form.label :issue_type %><br>
    <%= form.select :issue_type, options_for_select(sorted_issue_types.map { |t| [t[0].humanize, t[0]] }, @repair.issue_type) %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/repairs/show.html.erb
<p>
  <%= link_to 'Edit', edit_repair_path(@repair) if @admin %>
</p>

<p>
  <strong>Name:</strong>
  <%= @repair.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @repair.address %>
</p>

<p>
  <strong>Email:</strong>
  <%= @repair.email %>
</p>

<p>
  <strong>Issue Type:</strong>
  <%= @repair.issue_type.humanize %>
</p>

<p>
  <strong>Description:</strong>
  <%= @repair.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @repair.status.humanize %>
</p>

<% if @repair.updates.any? %>
  <h2>Updates</h2>
  <%= render @repair.updates %>
<% end %>

<% if @admin %>
  <h2>Add an update:</h2>
  <%= render 'repair_updates/form' %>
<% end %>

app/views/triage/done.html.erb
<p>
  Thanks for the report.
</p>

app/views/triage/end.html.erb
<p>
  Great!
</p>

<%= form_tag triage_start_path, method: :get do |form| %>
  <p>
    <%= submit_tag 'New issue', name: nil %>
  </p>
<% end %>

app/views/triage/offer_help.html.erb
<p>
  <%= @help_content %>
</p>

<%= form_tag triage_end_path, method: :get do |form| %>
  <%= hidden_field_tag :issue_type, @issue_type %>

  <p>
    Did that solve the problem?
    <%= submit_tag 'Yes', name: nil %>
    <%= submit_tag 'No', name: :no %>
  </p>
<% end %>

app/views/triage/select_issue_type.html.erb
<%= form_tag triage_solution_path, method: :get do |form| %>
  <p>
    What problem are you having?
  </p>

  <% sorted_issue_types.each do |issue_type| %>
    <p>
      <%= radio_button_tag :issue_type, issue_type[0] %> <%= label_tag :issue_type, issue_type[0].humanize %>
    </p>
  <% end %>

  <p>
    <%= submit_tag 'Submit', name: nil %>
  </p>
<% end %>

app/views/triage/solution.html.erb
<p>
  <%= @help_content %>
</p>

<%= form_tag triage_done_path, method: :get do |form| %>
  <%= hidden_field_tag :issue_type, @issue_type %>

  <p>
    Did that solve the problem?
    <%= submit_tag 'Yes', name: nil %>
    <%= submit_tag 'No', name: :no %>
  </p>
<% end %>

app/views/triage/start.html.erb
<%= form_tag triage_1_path, method: :get do |form| %>
  <p>
    What problem are you having?
  </p>

  <% sorted_issue_types.each do |issue_type| %>
    <p>
      <%= radio_button_tag :issue_type, issue_type[0] %> <%= label_tag :issue_type, issue_type[0].humanize %>
    </p>
  <% end %>

  <p>
    <%= submit_tag 'Submit', name: nil %>
  </p>
<% end %>